POST http://localhost:9090/register HTTP/1.1
Content-Type: application/json

# {
#     "username": "Anjali07",
#     "password": "linkedIn",
#     "email": "anjaligalav30424@gmail.com",
#     "name": "Anjali Galav"
# }
{
    "username": "Peeter18",
    "password": "linkedIn1",
    "email": "peeter@gmail.com",
    "name": "Peeter Parker"
}


###

POST http://localhost:9090/login HTTP/1.1
Content-Type: application/json

{
    "password": "linkedIn",
    "email": "anjaligalav30424@gmail.com"
}

###

GET http://localhost:9090/get_user_and_profile HTTP/1.1
Content-Type: application/json

{
    "token" : "521cc427de5df562cf90c55c8526ed36c2356ff6bf2ddc50a7b1c6f380440bd4"
} 

###

POST http://localhost:9090/update_profile_data HTTP/1.1
Content-Type: application/json

{
    "token" : "521cc427de5df562cf90c55c8526ed36c2356ff6bf2ddc50a7b1c6f380440bd4",
    "bio": "#WebDeveloper",
    "currentPost": "CTO",
    "pastWork": [
        {
            "company":"Microsoft",
            "position":"CTO",
            "years":"2+"
        }
    ],
    "education": [
        {
            "school":"IITB",
            "degree":"B.tech",
            "fieldOfStudy":"Programming"
        }
    ]
}  

###
GET http://localhost:9090/get_all_profiles HTTP/1.1

###
GET http://localhost:9090/posts HTTP/1.1



